MODULE GENUTIL
  ! general math and book keeping utilities

  IMPLICIT NONE

CONTAINS

SUBROUTINE REPLACESUBSTR(INSTRING,C,REPL)
    ! replace the last instance of the substring C in INSTRING with REPL
    IMPLICIT NONE
    CHARACTER*100, INTENT(INOUT) :: INSTRING
    CHARACTER(LEN=*), INTENT(IN) :: C
    CHARACTER(LEN=*), INTENT(IN) :: REPL
    INTEGER :: LENC, IND

    INSTRING = ADJUSTL(INSTRING)

    LENC = LEN_TRIM(C)

    IND = INDEX(INSTRING,C,.TRUE.)
    IF (IND.GT.0) THEN! if * was found in the string

       INSTRING = INSTRING(1:IND-1) // TRIM(ADJUSTL(REPL)) // INSTRING(IND+LENC:100)   
    END IF
  END SUBROUTINE REPLACESUBSTR

END MODULE GENUTIL
